tinyMCE.addI18n('en.smimage',{
desc : 'SMImage - Image manager',
button_ok_caption : 'OK',
button_save_caption : 'Save',
button_cancel_caption : 'Cancel',
menu_hint_11 : 'Upload file',
menu_hint_12 : 'Images',
menu_hint_2 : 'Create new folder',
menu_hint_3 : 'Back',
menu_hint_4 : 'Forward',
menu_hint_5 : 'Reload',
menu_view_select_1 : 'Thumbnail',
menu_view_select_2 : 'Table',
insert_label_1 : 'Description',
insert_label_2 : 'Title',
insert_label_3 : 'Alignment',
insert_label_4 : 'Style',
insert_alignment_1_hint : 'None',
insert_alignment_2_hint : 'Left',
insert_alignment_3_hint : 'Right',
table_column_caption_1 : 'File name',
table_column_caption_2 : 'File size',
table_column_caption_3 : 'Image size',
table_column_caption_4 : 'Date',
table_sort_hint_1 : 'Sort ascending',
table_sort_hint_2 : 'Sort descending',
upload_label_1 : 'File path',
upload_label_2 : 'File name',
upload_label_3 : 'New Image Size',
upload_label_4 : 'Filter',
upload_filter_select_1 : 'Grayscale',
upload_filter_select_2 : 'Grayscale 2',
upload_filter_select_3 : 'Sepia',
upload_info_1 : 'Maximum file size',
image_menu_caption_0 : 'Insert',
image_menu_caption_1 : 'Delete',
image_menu_caption_2 : 'Rename',
image_menu_caption_3 : 'Rotate Right',
image_menu_caption_4 : 'Rotate Left',
image_menu_hint_1 : 'Insert',
image_menu_hint_2 : 'Delete',
image_rename : 'New image name',
folder_rename : 'New folder name',
folder_new : 'New folder',
statusbar_item2_1 : 'Page',
statusbar_item2_2 : 'Files',
message_image_delete : 'Do you want to delete this file ?',
message_image_rename : 'Do you want to rename this file ?',
message_image_rotate : 'Do you want to rotate this image ?',
message_folder_rename : 'Do you want to rename this folder ?',
message_folder_delete : 'Do you want to delete this folder ?',
message_upload_1 : 'The file has not been uploaded to the server !',
message_upload_2 : 'No file was selected !',
message_upload_3 : 'Wrong file format !',
message_upload_4 : 'Wrong format !'
});