tinyMCE.addI18n('ru.smimage',{
desc : 'Менеджер изображений',
button_ok_caption : 'OK',
button_save_caption : 'Сохранить',
button_cancel_caption : 'Отмена',
menu_hint_11 : 'Загрузить изображение с копьютера',
menu_hint_12 : 'Изображения',
menu_hint_2 : 'Новая папка',
menu_hint_3 : 'Назад',
menu_hint_4 : 'Вперед',
menu_hint_5 : 'Обновить',
menu_view_select_1 : 'Иконки',
menu_view_select_2 : 'Список',
insert_label_1 : 'Описание',
insert_label_2 : 'Заголовок',
insert_label_3 : 'Выравнивание',
insert_label_4 : 'Стиль',
insert_alignment_1_hint : 'Нет',
insert_alignment_2_hint : 'Налево',
insert_alignment_3_hint : 'Направо',
table_column_caption_1 : 'Имя файла',
table_column_caption_2 : 'Объем',
table_column_caption_3 : 'Размеры',
table_column_caption_4 : 'Дата',
table_sort_hint_1 : 'Сортировать по возрастанию',
table_sort_hint_2 : 'Сортировать по убыванию',
upload_label_1 : 'Путь к файлу',
upload_label_2 : 'Имя файла',
upload_label_3 : 'Уменьшить до',
upload_label_4 : 'Фильтр',
upload_filter_select_1 : 'Градации серого',
upload_filter_select_2 : 'Градации серого 2',
upload_filter_select_3 : 'Сепия',
upload_info_1 : 'Максимальный размер файла',
image_menu_caption_0 : 'Вставить',
image_menu_caption_1 : 'Удалить',
image_menu_caption_2 : 'Переименовать',
image_menu_caption_3 : 'Повернуть направо',
image_menu_caption_4 : 'Повернуть налево',
image_menu_hint_1 : 'Вставить',
image_menu_hint_2 : 'Удалить',
image_rename : 'Новое имя изображения',
folder_rename : 'Новое имя папки',
folder_new : 'Новая папка',
statusbar_item2_1 : 'Страница',
statusbar_item2_2 : 'Файлов',
message_image_delete : 'Вы действительно хотите удалить этот файл?',
message_image_rename : 'Вы действительно хотите переименовать этот файл?',
message_image_rotate : 'Вы действительно хотите повернуть это изображение?',
message_folder_rename : 'Вы действительно хотите переименовать эту папку?',
message_folder_delete : 'Вы действительно хотите удалить эту папку?',
message_upload_1 : 'Ошибка: файл не загружен на сервер',
message_upload_2 : 'Ошибка: файл не выбран',
message_upload_3 : 'Ошибка: неправильный формат файла',
message_upload_4 : 'Неверный формат!'
});