tinyMCE.addI18n('en.smexplorer',{
desc : 'SMExplorer - File manager',
insert : 'Link description',
menu_hint_1 : 'Upload file',
menu_hint_2 : 'Create new folder',
menu_hint_3 : 'Rename folder',
menu_hint_4 : 'Delete folder',
menu_hint_5 : 'Delete file(s)',
menu_hint_6 : 'Close view',
menu_hint_7 : 'Reload',
panel_folder_caption : 'Folder',
table_column_caption_1 : 'File name',
table_column_caption_2 : 'File size',
table_column_caption_3 : 'Date',
table_sort_hint_1 : 'Sort ascending',
table_sort_hint_2 : 'Sort descending',
upload_label_1 : 'File path',
upload_label_2 : 'File name',
upload_button_1 : 'Save',
upload_button_2 : 'Cancel',
upload_info_1 : 'Allowed file type(s)',
upload_info_2 : 'Maximum file size',
upload_info_11 : 'Unrestricted',
file_menu_hint_1 : 'Insert',
file_menu_hint_2 : 'Delete',
file_menu_hint_3 : 'Show',
file_delete : 'Do you want to delete this file ?',
files_delete: 'Do you want to delete the selected file(s) ?',
file_rename : 'Do you want to rename this file ?',
folder_delete : 'Do you want to delete this folder ?',
folder_rename : 'New folder name',
folder_new : 'New folder',
statusbar_item2_1 : 'Files',
message_upload_1 : 'The file has successfully been uploaded to the server.',
message_upload_2 : 'Error - The file has not been uploaded to the server !',
message_upload_3 : 'Error - No file was selected !'
});