tinyMCE.addI18n('ru.smexplorer',{
desc : 'Менеджер файлов',
insert : 'Название ссылки на файл',
menu_hint_1 : 'Загрузить файл',
menu_hint_2 : 'Создать новую папку',
menu_hint_3 : 'Переименовать папку',
menu_hint_4 : 'Удалить папку',
menu_hint_5 : 'Удалить файл(ы)',
menu_hint_6 : 'Закрыть просмотр',
menu_hint_7 : 'Обновить',
panel_folder_caption : 'Папка',
table_column_caption_1 : 'Имя файла',
table_column_caption_2 : 'Размер',
table_column_caption_3 : 'Дата',
table_sort_hint_1 : 'По возрастанию',
table_sort_hint_2 : 'По убыванию',
upload_label_1 : 'Путь к файлу',
upload_label_2 : 'Имя файла',
upload_button_1 : 'Сохранить',
upload_button_2 : 'Отмена',
upload_info_1 : 'Доступные типы файлов',
upload_info_2 : 'Максимальный размер',
upload_info_11 : 'Любой',
file_menu_hint_1 : 'Вставить',
file_menu_hint_2 : 'Удалить',
file_menu_hint_3 : 'Показать',
file_delete : 'Вы действительно хотите удалить этот файл?',
files_delete: 'Вы действительно хотите удалить выбранные файлы?',
file_rename : 'Вы действительно хотите переименовать файл?',
folder_delete : 'Вы действительно хотите удалить эту папку?',
folder_rename : 'Новое имя папки',
folder_new : 'Новая папка',
statusbar_item2_1 : 'Файлов',
message_upload_1 : 'Файл успешно загружен на сервер',
message_upload_2 : 'Ошибка: файл не загружен на сервер',
message_upload_3 : 'Ошибка: файл не выбран'
});