tinyMCE.addI18n('en.smeditimage',{
desc : 'SMEditImage - Edit image',
button_ok_caption : 'OK',
button_cancel_caption : 'Cancel',
label_1_caption : 'Description',
label_2_caption : 'Title',
label_3_caption : 'Alignment',
label_4_caption : 'Margin',
label_5_caption : 'Style',
label_6_caption : 'Size',
label_7_caption : 'Border',
label_8_caption : 'px',
alignment_1_hint : 'None',
alignment_2_hint : 'Left',
alignment_3_hint : 'Right',
size_1_hint : 'Width',
size_2_hint : 'Height',
size_lock_hint : 'Constrain proportions',
size_orig_hint : 'Show original size'
});